# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: cCRE
  - /optimizer: adamw
  - /scheduler: cosine_warmup
  - /callbacks: [base, checkpoint]

train:
  monitor: test/loss
  mode: min

task:
  _name_: lm
  loss: cross_entropy
  torchmetrics: ['perplexity', 'num_tokens']

encoder: null
decoder: null #was null, when try True, it subscripts into it
