[project]
channels = ["pytorch", "bioconda", "conda-forge", "nvidia/label/cuda-12.4.0"]
description = "Add a short description here"
name = "caduceus"
platforms = ["linux-64"]
version = "0.2.0"
channel-priority = "disabled"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
numpy = ">=2.2.2,<3"
pip = ">=25.0.1,<26"
jupyter = ">=1.1.1,<2"
seaborn = ">=0.13.2,<0.14"
pytorch-lightning = ">=2.5.0.post0,<3"
biopython = ">=1.85,<2"
datasets = ">=3.2.0,<4"
einops = ">=0.8.1,<0.9"
fsspec = ">=2024.9.0,<2025"
zarr = ">=2.18.4,<3"
pandas = ">=2.2.3,<3"
prettytable = ">=3.14.0,<4"
omegaconf = ">=2.3.0,<3"
pytest = ">=8.3.4,<9"
rich = ">=13.9.4,<14"
scikit-learn = ">=1.6.1,<2"
torchmetrics = ">=1.6.1,<2"
tqdm = ">=4.67.1,<5"
transformers = ">=4.48.3,<5"
wandb = ">=0.19.6,<0.20"
scipy = ">=1.15.1,<2"
yaml = ">=0.2.5,<0.3"
torchview = ">=0.2.6,<0.3"
git-lfs = ">=3.6.1,<4"
h5py = ">=3.12.1,<4"
cuda = {version = "==12.4.0", channel = "nvidia/label/cuda-12.4.0"}
cudnn = "*"
cuda-nvcc = {version = "*", channel = "nvidia/label/cuda-12.4.0"}
cuda-toolkit = "==12.4.0"
cuda-libraries = "==12.4.0"
cuda-libraries-dev = "==12.4.0"
cuda-runtime = "==12.4.0"
cuda-version = "==12.4.0"


[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu124" }
pysam = "*"
triton = "*"
enformer-pytorch = ">=0.8.10, <0.9"
liftover = ">=1.3.2, <2"
leidenalg = ">=0.10.2, <0.11"
logomaker = ">=0.8.6, <0.9"
pyfaidx = ">=0.8.1.3, <0.9"
