model_name: hyena-small
tokenizer_name: char
model_config:
  _name_: dna_embedding
  d_model: 128
  n_layer: 2
  d_inner: 512  # ${eval:4 * ${.d_model}}
  vocab_size: 173
  resid_dropout: 0.0
  embed_dropout: 0.1
  fused_mlp: False # figure out how to use fused MLP, maybe only with bf16 + a100
  fused_dropout_add_ln: False
  residual_in_fp32: True
  pad_vocab_size_multiple: 1
  return_hidden_state: True  # in 2nd position of output tuple (1st is logits)
  layer:
    _name_: hyena
    emb_dim: 5
    filter_order: 64
    local_order: 3
    l_max: 1026  # add 2 for ckpt
    modulate: True
    w: 10
    lr: 6e-4
    wd: 0.0
    lr_pos_emb: 0.0
    
train:
  d_output: 1  # number of classes

dataset:
  dataset_name: DNase # human_enhancers_cohn
  max_length: 1024
  d_output: 1 # num classes
  tokenizer_name: char
  batch_size: 128  # Per GPU