model_name: hyena-med
tokenizer_name: char
model_config:
  _name_: dna_embedding
  d_model: 256
  n_layer: 4
  d_inner: 1024  # ${eval:4 * ${.d_model}}
  vocab_size: 16
  resid_dropout: 0.0
  embed_dropout: 0.1
  fused_mlp: False # figure out how to use fused MLP, maybe only with bf16 + a100
  fused_dropout_add_ln: False
  residual_in_fp32: True
  pad_vocab_size_multiple: 1
  checkpoint_mixer: true
  checkpoint_mlp: true
  return_hidden_state: True  # in 2nd position of output tuple (1st is logits)
  layer:
    _name_: hyena
    emb_dim: 5
    filter_order: 64
    local_order: 3
    l_max: 32770  # add 2 for ckpt
    modulate: True
    w: 10
    lr: 6e-4
    wd: 0.0
    lr_pos_emb: 0.0
  bidirectional: false
    
train:
  d_output: 1  # number of classes

dataset:
  dataset_name: DNase # human_enhancers_cohn
  max_length: 32768
  d_output: 1 # num classes
  tokenizer_name: char
  batch_size: 128  # Per GPU