num_workers: ${eval:"len(__import__('os').sched_getaffinity(0))"}
pin_memory: True
drop_last: True
# batch_size: 50
# num_workers: 4
# pin_memory: True
# drop_last: True # We set this to true because of the recurrent state mechanism
